#include <algorithm>
#include <iostream>
#include <vector>

#include "autotune/autotune.hpp"
#include "autotune/tuners/line_search.hpp"

#include "autotune/continuous_parameter.hpp"

// defines kernel, put in single compilation unit
AUTOTUNE_DECLARE_DEFINE_KERNEL(int(int), add_one)

int main(void) {
  autotune::add_one.set_verbose(true);
  autotune::add_one.set_source_dir("examples/kernel_minimal");

  // register parameters
  autotune::add_one.add_parameter("ADD_ONE", {"0", "1"});

  std::function<bool(int)> test_result = [](int) -> bool {
    /* tests values generated by kernel */
    return true;
  };

  int a = 5;

  size_t line_search_iterations = 1;
  autotune::tuners::line_search<decltype(autotune::add_one)> tuner(
      autotune::add_one, line_search_iterations, 1);
  tuner.setup_test(test_result);
  autotune::parameter_set optimal_parameter_indices = tuner.tune(a);
  autotune::add_one.set_parameters(optimal_parameter_indices);

  // // std::cout << "-------- final compilation ---------" << std::endl;
  // // std::vector<size_t> optimal_parameter_indices = {0};
  // autotune::add_one.create_parameter_file(optimal_parameter_indices);
  // autotune::add_one.compile();
  // // std::cout << "-------- final kernel call ---------" << std::endl;
  // autotune::add_one(a);
  return 0;
}
