#include <algorithm>
#include <iostream>
#include <vector>

#include "autotune/parameter.hpp"
#include "autotune/tuners/monte_carlo.hpp"
#include "autotune/tuners/randomizable_set.hpp"

// defines kernel, put in single compilation unit
AUTOTUNE_KERNEL(int(int), smooth_cost_function,
                "examples/kernel_smooth_cost_function")

int main(void) {

  autotune::randomizable_set parameters;
  autotune::limited_continuous_parameter p1("PAR_1", 1.0, 1.0, 5.0, true);
  parameters.add_parameter(p1);

  autotune::limited_continuous_parameter p2("PAR_2", 1.0, 1.0, 5.0, false);
  parameters.add_parameter(p2);

  std::function<bool(int)> test_result = [](int) -> bool {
    /* tests values generated by kernel */
    return true;
  };

  int a = 5;

  autotune::tuners::monte_carlo tuner(autotune::smooth_cost_function,
                                      parameters, 10);
  tuner.setup_test(test_result);
  tuner.set_verbose(true);
  autotune::randomizable_set optimal_parameters = tuner.tune(a);
  autotune::smooth_cost_function.set_parameter_values(optimal_parameters);
  optimal_parameters.print_values();

  return 0;
}
